from dataclasses import dataclass


@dataclass
class Entry:
    """
    Dataclass that represents an entry of the csv file.
    """

    age: int
    sex: str
    tension: int
    cholestrol: int
    bpm: int
    has_desease: bool

    @classmethod
    def from_line(cls, entry: list[str]) -> 'Entry':
        """
        Builds an Entry from a list of strings generated by the csv built-in module.

        :param entry: Entry as a list of strings.
        :return: The class Entry generated from entry.
        """
        return cls(
            int(entry[0]),
            entry[1],
            int(entry[2]),
            int(entry[3]),
            int(entry[4]),
            bool(int(entry[5]))
        )

